---
- name: Restart Prometheus container
  docker_container:
    name: prometheus
    state: stopped

- name: Start Prometheus container
  docker_container:
    name: prometheus
    state: started
    image: prom/prometheus
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /home/{{ ansible_user }}/prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
