apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3  # Change this to the desired EBS volume type (e.g., io1, gp3)
reclaimPolicy: Retain
volumeBindingMode: Immediate