apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            # - name: MONGO_INITDB_ROOT_USERNAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: expensy-config
            #       key: MONGO_INITDB_ROOT_USERNAME
            # - name: MONGO_INITDB_ROOT_PASSWORD
            #   valueFrom:
            #     configMapKeyRef:
            #       name: expensy-config
            #       key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "example"
          command: ["mongod", "--bind_ip_all"]
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db

      volumes:
        - name: mongo-data

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb

#          volumeMounts:
#            - name: mongodb-storage
#              mountPath: /data/db
#      volumes:
#        - name: mongodb-storage
#          persistentVolumeClaim:
#            claimName: mongo-pvc

