apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  spec:
    replicas: 1
    selector:
      matchLables:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: Tawfeeqm/backend:latest
# We need to make sure this is the correct image we want to use
          ports:
          - containerPort: 8706

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8706
    targetPort: 8706
  selector:
    app: backend
# Same as frontend. Create the deployment and the loadbalancer.