---
- name: Create Grafana Docker volume
  docker_volume:
    name: grafana-storage
    state: present

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana-oss
    state: started
    restart_policy: always
    ports:
      - "3333:3333"
    volumes:
      - grafana-storage:/var/lib/grafana
  notify: Restart Grafana container
