---
- name: Create Prometheus Docker volume
  docker_volume:
    name: prometheus-data
    state: present

- name: Create Prometheus config directory
  file:
    path: /home/{{ monitoring_ansible_user }}/prometheus-config
    state: directory
    owner: "{{ monitoring_ansible_user }}"
    group: "{{ monitoring_ansible_user }}"
    mode: '0755'

- name: Create Prometheus configuration file
  copy:
    dest: /home/{{ monitoring_ansible_user }}/prometheus-config/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['{{ monitoring_ansible_host }}:9100']
      - job_name: cadvisor
        scrape_interval: 5s
        static_configs:
        - targets: ['{{ monitoring_ansible_host }}:8080']

  notify:
    - Restart Prometheus container

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /home/{{ monitoring_ansible_user }}/prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus

